### PR TITLE
Fix the PluginLoader effectively being immortal

### PR DESCRIPTION
**Pull request by leofeyer**
Unfortunately, there is still a problem with the changes. I have required `contao/manager-plugin` in version `2.12.x-dev`. After trying to install the dependencies of the calendar bundle, the following error occurred:

### CODE REVIEW

**Comment by Toflar** [comment]
So this does not happen with `contao/contao` or the ME but with a single bundle only or what exactly do I have to do to reproduce this?

**Comment by leofeyer** [comment]
Yes.

* `cd calendar-bundle`
* `vi composer.json` (require `contao/manager-plugin` as `2.12.x-dev`)
* `COMPOSER_ROOT_VERSION=5.0.x-dev composer up`

**Comment by Toflar** [comment]
https://github.com/contao/manager-plugin/pull/52 should fix the issue

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
