### PR TITLE
Load artifacts from the project directory

### PR DESCRIPTION
**Pull request by aschempp**
Our composer plugin automatically registers the ZIP packages (uploads) folder from Contao Manager as a package repository. When running as the Contao Manager, the Composer `data-dir` is the `contao-manager` folder. However, this "breaks" when running as a regular composer command. This PR fixes that problem (I know there have been issues reported about it, but I couldn't find them).

### CODE REVIEW

**Review by leofeyer — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]
Should have a test for that though...

**Comment by aschempp** [comment]
@leofeyer can you please also update the CI chain to check for PHP8.1 and maybe re-run periodically?

**Comment by leofeyer** [comment]
You can do it yourself by adjusting the `.github/workflows/ci.yml` file according to your needs. Or do you know that already and just want me to do it? 😄

**Comment by aschempp** [comment]
> You can do it yourself by adjusting the `.github/workflows/ci.yml` file according to your needs. Or do you know that already and just want me to do it? 😄

I meant according to the `contao/contao` standard. Looks like the CS fixer is old as well, and maybe we should use a tools directory etc?

**Comment by leofeyer** [comment]
I will have a look. 👍

**Comment by leofeyer** [comment]
PR is here: https://github.com/contao/manager-plugin/pull/39 I don't know how to fix the two unit tests, though.

**Review by leofeyer — APPROVED** [review]

**Pull request merged**
